name: Build

on:
  pull_request:
    types: [ opened, edited, reopened, review_requested ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Configure line-endings for Windows builds
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: Setup Actions
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Analyze code with Deno linter
        run: deno lint

      - name: Run unit tests
        run: deno test -A --coverage=cov --doc

      - name: Generate coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: deno coverage --lcov cov > cov.lcov

      - name: Upload coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: cov.lcov
