name: Denopendabot
on:
  schedule:
    - cron: "0 19 * * *"
jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-22.04
    steps:
      - uses: hasundue/denopendabot@0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user-token: ${{ secrets.GH_TOKEN }}
