name: Publish Egg

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: setup deno
        uses: actions/checkout@v2
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
          
      - name: release
        run: |
          deno install -Af --unstable https://x.nest.land/eggs@0.3.8/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish
