name: Publish Egg

on:
  release:
    branches: 
    - main
    - ci_release
    types:
      - published
  

jobs:
  publish:
    environment: release
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Actions
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
           deno-version: v1.5.x
          
      - name: Release
        run: |
          deno install -Af --unstable https://x.nest.land/eggs@0.3.8/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish --yes --no-check --version $(git describe --tags $(git rev-list --tags --max-count=1))
